/**
 * useClinicalDocumentFlow
 * 
 * End-to-end flow for clinical documents:
 * - Create document (receita, atestado, relatório, etc.)
 * - Sign document → auto-generates validation_code via DB trigger
 * - Generate public validation URL
 * - List documents for a patient
 */

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useClinicData } from "@/hooks/useClinicData";
import { usePermissions } from "@/hooks/usePermissions";
import { toast } from "sonner";
import { logAudit } from "@/utils/auditLog";

export interface ClinicalDocument {
  id: string;
  clinic_id: string;
  patient_id: string;
  professional_id: string;
  document_type: string;
  title: string;
  content: Record<string, unknown>;
  status: "rascunho" | "assinado" | "cancelado";
  validation_code: string | null;
  signed_at: string | null;
  signed_by: string | null;
  pdf_url: string | null;
  created_at: string;
  updated_at: string;
}

export type DocumentType = "receita" | "atestado" | "relatorio" | "declaracao" | "encaminhamento" | "laudo" | "termo";

export const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  receita: "Receita",
  atestado: "Atestado",
  relatorio: "Relatório",
  declaracao: "Declaração",
  encaminhamento: "Encaminhamento",
  laudo: "Laudo",
  termo: "Termo",
};

interface CreateDocumentInput {
  patientId: string;
  documentType: DocumentType;
  title: string;
  content: Record<string, unknown>;
  signImmediately?: boolean;
}

export function useClinicalDocumentFlow(patientId: string | null) {
  const { clinic } = useClinicData();
  const { professionalId } = usePermissions();
  const queryClient = useQueryClient();

  // Fetch documents for a patient
  const { data: documents = [], isLoading } = useQuery({
    queryKey: ["clinical-documents", clinic?.id, patientId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("clinical_documents")
        .select("*")
        .eq("clinic_id", clinic!.id)
        .eq("patient_id", patientId!)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data as ClinicalDocument[];
    },
    enabled: !!clinic?.id && !!patientId,
  });

  // Create document
  const createDocument = useMutation({
    mutationFn: async (input: CreateDocumentInput) => {
      if (!clinic?.id || !professionalId) throw new Error("Dados de sessão incompletos");

      const user = (await supabase.auth.getUser()).data.user;
      const status = input.signImmediately ? "assinado" : "rascunho";

      const { data, error } = await supabase
        .from("clinical_documents")
        .insert({
          clinic_id: clinic.id,
          patient_id: input.patientId,
          professional_id: professionalId,
          document_type: input.documentType,
          title: input.title,
          content: input.content,
          status,
          signed_at: input.signImmediately ? new Date().toISOString() : null,
          signed_by: input.signImmediately ? user?.id : null,
          // validation_code auto-generated by DB trigger when status = 'assinado'
        })
        .select("id, validation_code")
        .single();

      if (error) throw error;

      if (input.signImmediately && data) {
        await logAudit({
          clinicId: clinic.id,
          action: "document_signed",
          entityType: "clinical_document",
          entityId: data.id,
          metadata: { document_type: input.documentType, patient_id: input.patientId },
        });
      }

      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["clinical-documents", clinic?.id, patientId] });
      if (data?.validation_code) {
        toast.success("Documento assinado e validação gerada", {
          description: `Código: ${data.validation_code.substring(0, 8)}...`,
        });
      } else {
        toast.success("Documento salvo como rascunho");
      }
    },
    onError: (err: Error) => {
      toast.error(err.message || "Erro ao criar documento");
    },
  });

  // Sign an existing draft document
  const signDocument = useMutation({
    mutationFn: async (documentId: string) => {
      if (!clinic?.id) throw new Error("Clínica não encontrada");

      const user = (await supabase.auth.getUser()).data.user;
      if (!user) throw new Error("Usuário não autenticado");

      const { data, error } = await supabase
        .from("clinical_documents")
        .update({
          status: "assinado" as any,
          signed_at: new Date().toISOString(),
          signed_by: user.id,
          // validation_code auto-generated by DB trigger
        })
        .eq("id", documentId)
        .eq("status", "rascunho")
        .select("id, validation_code")
        .single();

      if (error) throw error;

      await logAudit({
        clinicId: clinic.id,
        action: "document_signed",
        entityType: "clinical_document",
        entityId: documentId,
      });

      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["clinical-documents", clinic?.id, patientId] });
      toast.success("Documento assinado com sucesso");
    },
    onError: (err: Error) => {
      toast.error(err.message || "Erro ao assinar documento");
    },
  });

  // Get public validation URL
  const getValidationUrl = (documentId: string): string => {
    return `${window.location.origin}/validar/${documentId}`;
  };

  return {
    documents,
    isLoading,
    drafts: documents.filter(d => d.status === "rascunho"),
    signed: documents.filter(d => d.status === "assinado"),
    createDocument,
    signDocument,
    getValidationUrl,
    isEditable: (doc: ClinicalDocument) => doc.status === "rascunho",
  };
}
