import {
  LayoutDashboard,
  FileText,
  Stethoscope,
  Calendar,
  Paperclip,
  AlertTriangle,
  History,
  Activity,
  Pill,
  GitBranch,
  Heart,
  ClipboardList,
  Target,
  Smile,
  Crosshair,
  Camera,
  NotebookPen,
  MapPin,
  Goal,
  Route,
  BrainCircuit,
  PillIcon,
  TrendingUp,
  ClipboardCheck,
  Apple,
  Scale,
  Utensils,
  Sparkles,
  Syringe,
  ImageIcon,
  FileCheck,
  PersonStanding,
  MessageSquare,
  Gauge,
  Move,
  Dumbbell,
  BarChart3,
  ScrollText,
  Baby,
  Ruler,
  ShieldCheck,
  CircleUser,
  CalendarDays,
  HeartPulse,
  Search,
  Eye,
  Focus,
  Microscope,
  Package,
} from "lucide-react";

// Fallback nav items when no config exists
export const DEFAULT_NAV_ITEMS = [
  { id: 'resumo', label: 'Visão Geral', icon: LayoutDashboard },
  { id: 'tratamentos', label: 'Tratamentos/Sessões', icon: Package },
  { id: 'anamnese', label: 'Anamnese', icon: FileText },
  { id: 'sinais_vitais', label: 'Sinais Vitais', icon: Heart },
  { id: 'odontograma', label: 'Odontograma', icon: Smile },
  { id: 'tooth_procedures', label: 'Procedimentos por Dente', icon: Crosshair },
  { id: 'evolucao', label: 'Evoluções', icon: Activity },
  { id: 'diagnostico', label: 'Diagnóstico (CID)', icon: Stethoscope },
  { id: 'exames_solicitacao', label: 'Solicitar Exames', icon: ClipboardList },
  { id: 'conduta', label: 'Plano/Conduta', icon: Target },
  { id: 'documentos_clinicos', label: 'Documentos Clínicos', icon: ScrollText },

  { id: 'fotos_intraorais', label: 'Fotos Intraorais', icon: Camera },
  { id: 'exames', label: 'Exames / Documentos', icon: Paperclip },
  { id: 'timeline', label: 'Linha do Tempo', icon: GitBranch },
  { id: 'alertas', label: 'Alertas', icon: AlertTriangle },
  { id: 'historico', label: 'Histórico', icon: History },
  // Psychology tabs
  { id: 'session_record', label: 'Registro de Sessão', icon: NotebookPen },
  { id: 'therapeutic_goals', label: 'Objetivos Terapêuticos', icon: Goal },
  { id: 'therapeutic_plan', label: 'Plano Terapêutico', icon: Route },
  { id: 'plano_terapeutico', label: 'Plano Terapêutico', icon: Route },
  { id: 'plano_acao_crise', label: 'Plano de Ação em Crise', icon: ShieldCheck },
  // Psychiatry tabs
  { id: 'diagnosis_dsm', label: 'Diagnóstico (CID/DSM)', icon: BrainCircuit },
  { id: 'psychiatric_prescription', label: 'Prescrição Medicamentosa', icon: PillIcon },
  { id: 'symptom_evolution', label: 'Evolução de Sintomas', icon: TrendingUp },
  { id: 'medication_history', label: 'Histórico de Medicamentos', icon: ClipboardCheck },
// Nutrition tabs (usando os IDs corretos do sistema)
  { id: 'avaliacao_nutricional', label: 'Avaliação Nutricional Inicial', icon: Apple },
  { id: 'avaliacao_clinica', label: 'Avaliação Antropométrica', icon: Scale },
  { id: 'diagnostico_nutricional', label: 'Diagnóstico Nutricional', icon: ClipboardCheck },
  { id: 'plano_alimentar', label: 'Plano Alimentar', icon: Utensils },
  // Aesthetics tabs (using correct system IDs from yesclinSpecialties)
  { id: 'exame_fisico', label: 'Avaliação Estética', icon: Sparkles },
  { id: 'procedimentos_realizados', label: 'Procedimentos Realizados', icon: Syringe },
  { id: 'produtos_utilizados', label: 'Produtos Utilizados', icon: Package },

  { id: 'before_after_photos', label: 'Fotos Antes/Depois', icon: ImageIcon },
  { id: 'termos_consentimentos', label: 'Termos de Consentimento', icon: FileCheck },
  { id: 'facial_map', label: 'Mapa Facial', icon: MapPin },
  // Physiotherapy tabs (using correct system IDs)
  { id: 'avaliacao_funcional', label: 'Avaliação Funcional', icon: PersonStanding },
  { id: 'avaliacao_dor', label: 'Avaliação de Dor', icon: Gauge },
  { id: 'exercicios_prescritos', label: 'Exercícios Prescritos', icon: Dumbbell },
  { id: 'functional_assessment', label: 'Avaliação Funcional', icon: PersonStanding },
  { id: 'chief_complaint', label: 'Queixa Principal', icon: MessageSquare },
  { id: 'pain_scale', label: 'Escala de Dor', icon: Gauge },
  { id: 'range_of_motion', label: 'Amplitude de Movimento', icon: Move },
  { id: 'physio_therapeutic_plan', label: 'Plano Terapêutico', icon: ClipboardList },
  { id: 'applied_exercises', label: 'Exercícios Aplicados', icon: Dumbbell },
  { id: 'session_evolution', label: 'Evolução por Sessão', icon: BarChart3 },
  // Pediatrics tabs (correct system IDs from yesclinSpecialties)
  { id: 'anamnese_pediatrica', label: 'Anamnese Pediátrica', icon: Baby },
  { id: 'crescimento_desenvolvimento', label: 'Crescimento e Desenvolvimento', icon: Ruler },
  { id: 'avaliacao_clinica_pediatrica', label: 'Avaliação Clínica', icon: Stethoscope },
  { id: 'diagnostico_pediatrico', label: 'Diagnóstico Pediátrico', icon: ClipboardCheck },
  { id: 'prescricoes_pediatricas', label: 'Prescrições', icon: Pill },
  { id: 'vacinacao', label: 'Vacinação', icon: ShieldCheck },
  // Gynecology tabs
  { id: 'gyneco_anamnesis', label: 'Anamnese Ginecológica', icon: CircleUser },
  { id: 'gyneco_data', label: 'Dados Ginecológicos', icon: CalendarDays },
  { id: 'obstetric_history', label: 'Histórico Obstétrico (G/P/A)', icon: HeartPulse },
  { id: 'gyneco_exam', label: 'Exame Ginecológico', icon: Search },
  { id: 'gyneco_exams_results', label: 'Exames/Resultados', icon: ClipboardList },
  { id: 'gyneco_diagnosis', label: 'Diagnóstico', icon: Stethoscope },
  { id: 'gyneco_conduct', label: 'Conduta/Prescrição', icon: Target },
  { id: 'gyneco_evolution', label: 'Evolução Clínica', icon: Activity },
  // Ophthalmology tabs
  { id: 'ophthalmo_anamnesis', label: 'Anamnese Oftalmológica', icon: Eye },
  { id: 'visual_acuity', label: 'Acuidade Visual (OD/OE)', icon: Focus },
  { id: 'ophthalmo_exam', label: 'Exame Oftalmológico', icon: Microscope },
  { id: 'intraocular_pressure', label: 'Pressão Intraocular (OD/OE)', icon: Gauge },
  { id: 'ophthalmo_diagnosis', label: 'Diagnóstico (OD/OE)', icon: Stethoscope },
  { id: 'ophthalmo_complementary_exams', label: 'Exames Complementares', icon: ClipboardList },
  { id: 'ophthalmo_conduct', label: 'Conduta/Prescrição', icon: Target },
  { id: 'ophthalmo_evolution', label: 'Evolução Clínica', icon: Activity },
];
