-- Seed permission_templates for all roles and modules
DELETE FROM public.permission_templates WHERE is_system = true;

INSERT INTO public.permission_templates (role, module, actions, is_system) VALUES
  ('owner', 'dashboard', '{view,create,edit,delete,export}', true),
  ('owner', 'agenda', '{view,create,edit,delete,export}', true),
  ('owner', 'pacientes', '{view,create,edit,delete,export}', true),
  ('owner', 'prontuario', '{view,create,edit,delete,export}', true),
  ('owner', 'comunicacao', '{view,create,edit,delete,export}', true),
  ('owner', 'financeiro', '{view,create,edit,delete,export}', true),
  ('owner', 'meu_financeiro', '{view,create,edit,delete,export}', true),
  ('owner', 'convenios', '{view,create,edit,delete,export}', true),
  ('owner', 'estoque', '{view,create,edit,delete,export}', true),
  ('owner', 'relatorios', '{view,create,edit,delete,export}', true),
  ('owner', 'configuracoes', '{view,create,edit,delete,export}', true),
  ('admin', 'dashboard', '{view,create,edit,delete,export}', true),
  ('admin', 'agenda', '{view,create,edit,delete,export}', true),
  ('admin', 'pacientes', '{view,create,edit,delete,export}', true),
  ('admin', 'prontuario', '{view,create,edit,delete,export}', true),
  ('admin', 'comunicacao', '{view,create,edit,delete,export}', true),
  ('admin', 'financeiro', '{view,create,edit,delete,export}', true),
  ('admin', 'meu_financeiro', '{view,create,edit,delete,export}', true),
  ('admin', 'convenios', '{view,create,edit,delete,export}', true),
  ('admin', 'estoque', '{view,create,edit,delete,export}', true),
  ('admin', 'relatorios', '{view,create,edit,delete,export}', true),
  ('admin', 'configuracoes', '{view,create,edit,delete}', true),
  ('profissional', 'dashboard', '{view}', true),
  ('profissional', 'agenda', '{view,create,edit}', true),
  ('profissional', 'pacientes', '{view,create,edit}', true),
  ('profissional', 'prontuario', '{view,create,edit}', true),
  ('profissional', 'comunicacao', '{view}', true),
  ('profissional', 'financeiro', '{view}', true),
  ('profissional', 'meu_financeiro', '{view,export}', true),
  ('profissional', 'convenios', '{view}', true),
  ('profissional', 'estoque', '{view}', true),
  ('profissional', 'relatorios', '{view,export}', true),
  ('profissional', 'configuracoes', '{view}', true),
  ('recepcionista', 'dashboard', '{view}', true),
  ('recepcionista', 'agenda', '{view,create,edit}', true),
  ('recepcionista', 'pacientes', '{view,create,edit}', true),
  ('recepcionista', 'prontuario', '{}', true),
  ('recepcionista', 'comunicacao', '{view}', true),
  ('recepcionista', 'financeiro', '{view,create}', true),
  ('recepcionista', 'meu_financeiro', '{}', true),
  ('recepcionista', 'convenios', '{view}', true),
  ('recepcionista', 'estoque', '{view}', true),
  ('recepcionista', 'relatorios', '{}', true),
  ('recepcionista', 'configuracoes', '{}', true);