// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const readEnvString = (value: unknown) => (typeof value === 'string' ? value.trim() : '');

const SUPABASE_URL = readEnvString(import.meta.env.VITE_SUPABASE_URL);
// Usa a variável padrão pedida pelo app; mantém fallback para projetos Lovable
// que ainda expõem a mesma anon key como VITE_SUPABASE_PUBLISHABLE_KEY.
const SUPABASE_PUBLISHABLE_KEY = (
  readEnvString(import.meta.env.VITE_SUPABASE_ANON_KEY) ||
  readEnvString(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)
);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('[SUPABASE_CONFIG] VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY/VITE_SUPABASE_PUBLISHABLE_KEY são obrigatórios.');
}

// Diagnóstico em runtime para facilitar suporte quando o login falha.
if (typeof window !== 'undefined') {
  if (!/^https:\/\/[a-z0-9-]+\.supabase\.(co|in)$/i.test(SUPABASE_URL)) {
    console.warn('[SUPABASE_CONFIG] VITE_SUPABASE_URL com formato inesperado:', SUPABASE_URL);
  }
}

const SUPABASE_PROJECT_REF = (() => {
  try {
    return new URL(SUPABASE_URL).hostname.split('.')[0] || 'default';
  } catch {
    return 'default';
  }
})();

// Sanity check: ref do JWT (claim `ref`) deve bater com o hostname.
if (typeof window !== 'undefined' && SUPABASE_PUBLISHABLE_KEY && SUPABASE_PROJECT_REF !== 'default') {
  try {
    const payload = JSON.parse(
      window.atob(SUPABASE_PUBLISHABLE_KEY.split('.')[1].replace(/-/g, '+').replace(/_/g, '/'))
    );
    if (payload?.ref && payload.ref !== SUPABASE_PROJECT_REF) {
      console.error('[SUPABASE_CONFIG] ANON_KEY pertence a outro projeto Supabase', {
        urlRef: SUPABASE_PROJECT_REF, keyRef: payload.ref,
      });
    }
  } catch { /* ignore */ }
}

export const LEGACY_SUPABASE_AUTH_STORAGE_KEY = `sb-${SUPABASE_PROJECT_REF}-auth-token`;

const TAB_ID_SESSION_KEY = 'yc.auth.tabId';
const TAB_ID_WINDOW_NAME_PREFIX = 'yesclin-auth-tab:';
// Binding persistente por aba — guarda o userId esperado para que o backup em
// localStorage só seja aceito se bater EXATAMENTE com este userId.
const TAB_BINDING_PREFIX = 'yc.auth.bind.';

function createTabId() {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return crypto.randomUUID();
  }
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}

function getStableTabId() {
  if (typeof window === 'undefined') return 'server';
  try {
    const nameMatch = window.name.match(new RegExp(`${TAB_ID_WINDOW_NAME_PREFIX}([a-zA-Z0-9-]+)`));
    if (nameMatch?.[1]) {
      // Mantém em sessionStorage também (alguns browsers limpam window.name em navegação cross-origin)
      try { window.sessionStorage.setItem(TAB_ID_SESSION_KEY, nameMatch[1]); } catch { /* ignore */ }
      return nameMatch[1];
    }

    const sessionTabId = window.sessionStorage.getItem(TAB_ID_SESSION_KEY);
    if (sessionTabId) {
      window.name = window.name
        ? `${window.name}|${TAB_ID_WINDOW_NAME_PREFIX}${sessionTabId}`
        : `${TAB_ID_WINDOW_NAME_PREFIX}${sessionTabId}`;
      return sessionTabId;
    }

    const tabId = createTabId();
    window.sessionStorage.setItem(TAB_ID_SESSION_KEY, tabId);
    window.name = window.name
      ? `${window.name}|${TAB_ID_WINDOW_NAME_PREFIX}${tabId}`
      : `${TAB_ID_WINDOW_NAME_PREFIX}${tabId}`;
    return tabId;
  } catch {
    return createTabId();
  }
}

function decodeJwtSub(token: string | null | undefined) {
  if (!token) return null;
  try {
    const payload = token.split('.')[1];
    if (!payload) return null;
    const normalized = payload.replace(/-/g, '+').replace(/_/g, '/');
    const json = JSON.parse(window.atob(normalized));
    return typeof json?.sub === 'string' ? json.sub : null;
  } catch {
    return null;
  }
}

function extractSessionUserId(rawSession: string | null) {
  if (!rawSession || typeof window === 'undefined') return null;
  try {
    const parsed = JSON.parse(rawSession);
    if (typeof parsed?.user?.id === 'string') return parsed.user.id;
    return decodeJwtSub(parsed?.access_token);
  } catch {
    return null;
  }
}

const CURRENT_TAB_ID = getStableTabId();
export const CURRENT_AUTH_STORAGE_KEY = `yc.auth.${SUPABASE_PROJECT_REF}.${CURRENT_TAB_ID}`;
const CURRENT_TAB_BINDING_KEY = `${TAB_BINDING_PREFIX}${SUPABASE_PROJECT_REF}.${CURRENT_TAB_ID}`;

export function isYesclinScopedAuthStorageKey(key: string) {
  return key.startsWith(`yc.auth.${SUPABASE_PROJECT_REF}.`);
}

const BIND_KEY_PREFIX_FOR_PROJECT = `${TAB_BINDING_PREFIX}${SUPABASE_PROJECT_REF}.`;
const SESSION_KEY_PREFIX_FOR_PROJECT = `yc.auth.${SUPABASE_PROJECT_REF}.`;

/**
 * Quando a aba nova não tem binding (ex.: iframe recriado, reload do preview,
 * sessionStorage limpo), tentamos restaurar com segurança: se TODAS as
 * identidades YesClin já conhecidas neste navegador apontam para o MESMO
 * userId, é seguro adotá-lo. Se houver mais de uma identidade, retornamos null
 * e o usuário cai em /login — não escolhemos entre contas.
 */
function resolveSoleStoredIdentity(): string | null {
  if (typeof window === 'undefined') return null;
  try {
    const ids = new Set<string>();
    const scan = (store: Storage) => {
      for (let i = 0; i < store.length; i++) {
        const key = store.key(i);
        if (!key) continue;
        if (key.startsWith(BIND_KEY_PREFIX_FOR_PROJECT)) {
          const value = store.getItem(key);
          if (value) ids.add(value);
        } else if (key.startsWith(SESSION_KEY_PREFIX_FOR_PROJECT)) {
          const userId = extractSessionUserId(store.getItem(key));
          if (userId) ids.add(userId);
        }
      }
    };
    scan(window.localStorage);
    scan(window.sessionStorage);
    if (ids.size === 1) return [...ids][0];
    return null;
  } catch {
    return null;
  }
}

function readTabBinding(): string | null {
  if (typeof window === 'undefined') return null;
  try {
    // Prioriza sessionStorage (vivo durante a sessão da aba); cai para
    // localStorage com a mesma chave de aba (persistente entre reloads/iframe).
    const direct =
      window.sessionStorage.getItem(CURRENT_TAB_BINDING_KEY) ||
      window.localStorage.getItem(CURRENT_TAB_BINDING_KEY);
    if (direct) return direct;
    // Fallback seguro: única identidade conhecida no navegador.
    const sole = resolveSoleStoredIdentity();
    if (sole) {
      writeTabBinding(sole);
      return sole;
    }
    return null;
  } catch {
    return null;
  }
}

function writeTabBinding(userId: string) {
  if (typeof window === 'undefined') return;
  try {
    window.sessionStorage.setItem(CURRENT_TAB_BINDING_KEY, userId);
    window.localStorage.setItem(CURRENT_TAB_BINDING_KEY, userId);
  } catch {
    /* ignore */
  }
}

function clearTabBinding() {
  if (typeof window === 'undefined') return;
  try {
    window.sessionStorage.removeItem(CURRENT_TAB_BINDING_KEY);
    window.localStorage.removeItem(CURRENT_TAB_BINDING_KEY);
  } catch {
    /* ignore */
  }
}

/**
 * Remove TODOS os bindings e sessões YesClin órfãos deste projeto em ambos
 * os storages. Usado em logout/quarentena para impedir que backups antigos
 * "ressuscitem" via resolveSoleStoredIdentity em uma aba futura.
 */
export function purgeAllProjectAuthStorage() {
  if (typeof window === 'undefined') return;
  try {
    for (const store of [window.localStorage, window.sessionStorage]) {
      const toRemove: string[] = [];
      for (let i = 0; i < store.length; i++) {
        const key = store.key(i);
        if (!key) continue;
        if (
          key.startsWith(BIND_KEY_PREFIX_FOR_PROJECT) ||
          key.startsWith(SESSION_KEY_PREFIX_FOR_PROJECT)
        ) {
          toRemove.push(key);
        }
      }
      toRemove.forEach((key) => store.removeItem(key));
    }
  } catch {
    /* ignore */
  }
}

/**
 * Adapter de storage do Supabase com isolamento estrito por aba.
 *
 * REGRAS DE SEGURANÇA (não relaxar):
 *  - Backup em localStorage SÓ pode hidratar a sessão se o userId do token
 *    bater com o binding persistente da aba. Sem binding ou divergente:
 *    descartamos silenciosamente — a pessoa cai no /login.
 *  - Quando a aba nova não tem binding (iframe recriado, reload do preview),
 *    aceitamos restaurar APENAS se houver uma única identidade YesClin
 *    conhecida no navegador (resolveSoleStoredIdentity). Havendo duas ou
 *    mais contas armazenadas, NUNCA escolhemos por o usuário.
 *  - setItem grava binding do userId autenticado ao mesmo tempo que a sessão.
 *  - removeItem limpa sessão + binding da aba atual.
 */
const perTabAuthStorage = {
  getItem: (key: string) => {
    if (typeof window === 'undefined') return null;
    const tabValue = window.sessionStorage.getItem(key);
    if (tabValue) {
      if (key === CURRENT_AUTH_STORAGE_KEY) {
        const userId = extractSessionUserId(tabValue);
        const expected = readTabBinding();
        if (userId && expected && userId !== expected) {
          // Sessão divergente do binding da aba — bloqueia.
          console.error('[AUTH_SECURITY] sessionStorage com user divergente do binding da aba — descartando', {
            tabExpected: expected, sessionUserId: userId,
          });
          window.sessionStorage.removeItem(key);
          return null;
        }
        if (userId && !expected) {
          // Primeiro uso desta aba — fixa o binding.
          writeTabBinding(userId);
        }
      }
      return tabValue;
    }

    if (key === CURRENT_AUTH_STORAGE_KEY) {
      const backup = window.localStorage.getItem(key);
      if (!backup) return null;
      const userId = extractSessionUserId(backup);
      const expected = readTabBinding();
      // Restauração SÓ permitida quando há binding válido para ESTA aba e
      // o backup pertence exatamente ao mesmo usuário. Sem binding, NÃO
      // restauramos — preferimos enviar para /login a aceitar outra conta.
      if (!userId || !expected || userId !== expected) {
        if (!expected) {
          if (import.meta.env.DEV) {
            console.warn('[AUTH_SECURITY] backup ignorado — aba sem binding de identidade');
          }
        } else if (userId !== expected) {
          console.error('[AUTH_SECURITY] backup ignorado — userId divergente do binding da aba', {
            tabExpected: expected, backupUserId: userId,
          });
        }
        return null;
      }
      window.sessionStorage.setItem(key, backup);
      return backup;
    }

    return null;
  },
  setItem: (key: string, value: string) => {
    if (typeof window === 'undefined') return;
    window.sessionStorage.setItem(key, value);
    if (key === CURRENT_AUTH_STORAGE_KEY) {
      const userId = extractSessionUserId(value);
      const expected = readTabBinding();
      if (userId && expected && userId !== expected) {
        // Tentativa de gravar sessão de outro usuário nesta aba — NÃO
        // persiste no localStorage e descarta do sessionStorage também.
        console.error('[AUTH_SECURITY] setItem bloqueado — sessão de user divergente do binding da aba', {
          tabExpected: expected, sessionUserId: userId,
        });
        window.sessionStorage.removeItem(key);
        return;
      }
      if (userId) {
        writeTabBinding(userId);
        window.localStorage.setItem(key, value);
      } else {
        // Sem userId identificável — não persiste backup em localStorage.
        window.localStorage.removeItem(key);
      }
    } else {
      window.localStorage.setItem(key, value);
    }
  },
  removeItem: (key: string) => {
    if (typeof window === 'undefined') return;
    window.localStorage.removeItem(key);
    window.sessionStorage.removeItem(key);
    if (key === CURRENT_AUTH_STORAGE_KEY) {
      clearTabBinding();
    }
  },
};

/**
 * API pública para os fluxos de login/logout sincronizarem o binding da aba
 * com a identidade autenticada — evita janelas de race em que o storage
 * recebe a sessão antes do binding existir.
 */
export function rememberTabIdentity(userId: string) {
  if (!userId) return;
  writeTabBinding(userId);
}

export function clearTabIdentity() {
  clearTabBinding();
  if (typeof window === 'undefined') return;
  try {
    window.localStorage.removeItem(CURRENT_AUTH_STORAGE_KEY);
    window.sessionStorage.removeItem(CURRENT_AUTH_STORAGE_KEY);
  } catch {
    /* ignore */
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const _supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Isolamento por aba: evita que o login de B em outra aba sobrescreva o
    // JWT de A via localStorage compartilhado e gere janela de race no cache.
    storage: perTabAuthStorage,
    storageKey: CURRENT_AUTH_STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
    // CRÍTICO para o fluxo de auth não voltar para /login após login/recovery:
    // detecta tokens em querystring/hash e troca por sessão persistida.
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});

// Export as any to bypass empty Database type definitions until types are regenerated
export const supabase: any = _supabase;
